"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Camera, Check, Crop, ImagePlus, Loader2, Plus, RotateCcw, RotateCw, Save, Trash2, X } from "lucide-react";
import { uploadProductImage } from "@/lib/product-image-upload-client";

type Category = { id: string; name: string };
type Form = { name: string; slug: string; categoryId: string; isActive: boolean; price: string; stock: string; rating: string; flavor: string; size: string; badge: string };
type Photo = { file: File; url: string; name: string; original: number; final: number };
type CropArea = { x: number; y: number; size: number };
const blank: Form = { name: "", slug: "", categoryId: "", isActive: true, price: "", stock: "0", rating: "5", flavor: "", size: "", badge: "" };
const TARGET = 950_000; const TYPES = ["image/jpeg", "image/png", "image/webp"];
const slugify = (v: string) => v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const size = (n: number) => n >= 1e6 ? `${(n / 1e6).toFixed(1)} MB` : `${Math.round(n / 1000)} KB`;

async function optimize(file: File, rotation = 0, crop?: CropArea) {
  const image = "createImageBitmap" in window ? await createImageBitmap(file) : await new Promise<HTMLImageElement>((ok, fail) => { const img = new window.Image(); const url = URL.createObjectURL(file); img.onload = () => { URL.revokeObjectURL(url); ok(img); }; img.onerror = fail; img.src = url; });
  const sx = crop ? image.width * crop.x : 0; const sy = crop ? image.height * crop.y : 0; const sw = crop ? image.width * crop.size : image.width; const sh = crop ? image.height * crop.size : image.height; let scale = Math.min(1, 2200 / Math.max(sw, sh)); let output: Blob | null = null;
  for (let pass = 0; pass < 8; pass++) { const w = Math.max(1, Math.round(sw * scale)); const h = Math.max(1, Math.round(sh * scale)); const turned = Math.abs(rotation % 180) === 90; const canvas = document.createElement("canvas"); canvas.width = turned ? h : w; canvas.height = turned ? w : h; const context = canvas.getContext("2d"); if (!context) throw new Error(); context.translate(canvas.width / 2, canvas.height / 2); context.rotate(rotation * Math.PI / 180); context.drawImage(image, sx, sy, sw, sh, -w / 2, -h / 2, w, h); output = await new Promise(resolve => canvas.toBlob(resolve, "image/webp", [0.85, 0.75, 0.65, 0.55][Math.min(pass, 3)])); if (output && output.size <= TARGET) break; if (pass >= 3) scale *= .8; }
  if ("close" in image && typeof image.close === "function") image.close(); if (!output || output.size > TARGET) throw new Error(); return output;
}

export default function ProductCreationStudio() {
  const [form, setForm] = useState(blank); const [categories, setCategories] = useState<Category[]>([]); const [photo, setPhoto] = useState<Photo | null>(null); const [source, setSource] = useState<File | null>(null); const [temporaryUrl, setTemporaryUrl] = useState(""); const [previewFailed, setPreviewFailed] = useState(false); const [rotation, setRotation] = useState(0); const [crop, setCrop] = useState<CropArea | undefined>(); const [cropOpen, setCropOpen] = useState(false); const [cropBeforeEdit, setCropBeforeEdit] = useState<CropArea | undefined>(); const [cameraOpen, setCameraOpen] = useState(false); const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [processing, setProcessing] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState(false); const fileRef = useRef<HTMLInputElement>(null); const cameraRef = useRef<HTMLInputElement>(null); const videoRef = useRef<HTMLVideoElement>(null); const cropRef = useRef<HTMLDivElement>(null); const streamRef = useRef<MediaStream | null>(null); const pointerRef = useRef<{ mode: "move" | "resize"; handle?: string; startX: number; startY: number; start: CropArea } | null>(null);
  useEffect(() => { void fetch("/api/categories").then(async r => { const body = await r.json() as { data?: Category[] }; if (!r.ok) throw new Error(); setCategories(body.data ?? []); }).catch(() => setError("Kategori belum dapat dimuat. Silakan muat ulang halaman.")); }, []); useEffect(() => () => { if (photo) URL.revokeObjectURL(photo.url); }, [photo]); useEffect(() => () => { if (temporaryUrl) URL.revokeObjectURL(temporaryUrl); }, [temporaryUrl]); useEffect(() => () => streamRef.current?.getTracks().forEach(track => track.stop()), []);
  const category = categories.find(c => c.id === form.categoryId); const parcel = category?.name.trim().toLowerCase() === "parcel"; const items = useMemo(() => form.flavor.split(",").map(v => v.trim()).filter(Boolean), [form.flavor]); const set = (key: keyof Form, value: string | boolean) => setForm(current => ({ ...current, [key]: value, ...(key === "name" ? { slug: slugify(String(value)) } : {}) }));
  async function process(file: File, turn = 0, area?: CropArea) { setError(""); setPreviewFailed(false); if (!TYPES.includes(file.type)) return setError("Gunakan foto JPEG, PNG, atau WebP."); setProcessing(true); try { const blob = await optimize(file, turn, area); const final = new File([blob], `${slugify(file.name.replace(/\.[^.]+$/, "")) || "produk"}.webp`, { type: "image/webp" }); setPhoto({ file: final, url: URL.createObjectURL(final), name: file.name, original: file.size, final: final.size }); } catch { setError("Foto tidak dapat diproses."); } finally { setProcessing(false); } }
  function choose(file?: File) { if (!file) return; setPhoto(null); setSource(file); setTemporaryUrl(URL.createObjectURL(file)); setPreviewFailed(false); setRotation(0); setCrop(undefined); void process(file); }
  function edit(turn: number, area?: CropArea) { if (!source) return; setRotation(turn); setCrop(area); void process(source, turn, area); }
  function beginCrop() { if (!source) return; const initial = crop ?? { x: 0, y: 0, size: 1 }; setCropBeforeEdit(initial); setCrop(initial); setCropOpen(true); }
  function updateCrop(event: React.PointerEvent<HTMLSpanElement>, mode: "move" | "resize", handle?: string) { if (!crop || !cropRef.current) return; event.currentTarget.setPointerCapture(event.pointerId); pointerRef.current = { mode, handle, startX: event.clientX, startY: event.clientY, start: crop }; }
  function moveCrop(event: React.PointerEvent<HTMLDivElement>) { const active = pointerRef.current; if (!active || !crop || !cropRef.current) return; const rect = cropRef.current.getBoundingClientRect(); const dx = (event.clientX - active.startX) / rect.width; const dy = (event.clientY - active.startY) / rect.height; const min = 0.2; const next = { ...active.start }; if (active.mode === "move") { next.x = Math.max(0, Math.min(1 - next.size, active.start.x + dx)); next.y = Math.max(0, Math.min(1 - next.size, active.start.y + dy)); } else { const delta = active.handle?.includes("left") || active.handle?.includes("top") ? -Math.min(dx, dy) : Math.max(dx, dy); const size = Math.max(min, Math.min(1, active.start.size + delta)); next.size = size; if (active.handle?.includes("left")) next.x = Math.max(0, Math.min(1 - size, active.start.x + active.start.size - size)); if (active.handle?.includes("top")) next.y = Math.max(0, Math.min(1 - size, active.start.y + active.start.size - size)); next.x = Math.max(0, Math.min(next.x, 1 - size)); next.y = Math.max(0, Math.min(next.y, 1 - size)); } setCrop(next); }
  function endCrop() { pointerRef.current = null; }
  function stopCamera() { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setCameraOpen(false); }
  async function openCamera() { if (window.matchMedia("(pointer: coarse)").matches) { cameraRef.current?.click(); return; } if (!navigator.mediaDevices?.getUserMedia || !window.isSecureContext) { setError("Kamera tidak dapat digunakan. Silakan gunakan Upload Foto."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); streamRef.current = stream; setCameraOpen(true); requestAnimationFrame(() => { if (videoRef.current) { videoRef.current.srcObject = stream; void videoRef.current.play(); } }); } catch { stopCamera(); setError("Kamera tidak dapat digunakan. Silakan gunakan Upload Foto."); } }
  async function captureCamera() { const video = videoRef.current; if (!video?.videoWidth) return; const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0); const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, "image/jpeg", .92)); stopCamera(); if (blob) choose(new File([blob], `camera-${Date.now()}.jpg`, { type: "image/jpeg" })); }
  function removePhoto() { setPhoto(null); setSource(null); setTemporaryUrl(""); setPreviewFailed(false); setRotation(0); setCrop(undefined); setCropOpen(false); if (fileRef.current) fileRef.current.value = ""; if (cameraRef.current) cameraRef.current.value = ""; } function reset() { setForm(blank); removePhoto(); setDraft(""); setError(""); setDone(false); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const price = Number(form.price), stock = Number(form.stock), rating = Number(form.rating); if (!form.name.trim()) return setError("Nama produk wajib diisi."); if (!form.categoryId) return setError("Kategori wajib dipilih."); if (form.price === "" || !Number.isInteger(price) || price < 0) return setError("Harga tidak valid."); if (form.stock === "" || !Number.isInteger(stock) || stock < 0) return setError("Stok tidak valid."); if (photo && photo.file.size > 1024 * 1024) return setError("Ukuran gambar terlalu besar."); setBusy(true); try { let image: string | null = null; if (photo) image = (await uploadProductImage(photo.file)).url; const response = await fetch("/api/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, name: form.name.trim(), slug: form.slug || slugify(form.name), categoryId: form.categoryId, price, stock, rating, flavor: form.flavor || null, size: form.size || null, badge: form.badge || null, image }) }); if (!response.ok) throw new Error("Produk gagal disimpan. Silakan coba lagi."); setDone(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Produk gagal disimpan. Silakan coba lagi."); } finally { setBusy(false); } }
  if (done) return <main className="studio-page"><div className="studio-success"><Check size={44} /><h1>Produk berhasil ditambahkan.</h1><p>Produk telah disimpan melalui API produk AFA STORE.</p><div><Link href="/admin/products">Lihat Produk</Link><button onClick={reset}>Tambah Produk Lagi</button></div></div></main>;
  return <main className="studio-page"><div className="studio-shell"><header className="studio-heading"><div><Link href="/admin/products">← Kembali ke Produk</Link><p>AFA STORE ADMIN</p><h1>Product Creation Studio</h1><span>Tambahkan produk baru ke katalog AFA STORE</span></div><b>Produk Baru</b></header><form onSubmit={submit} className="studio-layout"><div className="studio-sections">
    <Section n="01" title="Informasi Produk"><Grid><Field id="name" label="Nama Produk"><input required value={form.name} onChange={e => set("name", e.target.value)} /></Field><Field id="slug" label="Slug otomatis" help="Terbentuk otomatis dan tetap dapat diedit."><input required value={form.slug} onChange={e => set("slug", slugify(e.target.value))} /></Field><Field id="category" label="Kategori"><select required value={form.categoryId} onChange={e => set("categoryId", e.target.value)}><option value="">Pilih kategori</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field id="status" label="Status Produk"><select value={form.isActive ? "on" : "off"} onChange={e => set("isActive", e.target.value === "on")}><option value="on">Aktif</option><option value="off">Nonaktif</option></select></Field></Grid></Section>
    <Section n="02" title="Harga & Persediaan"><Grid three><Field id="price" label="Harga"><div className="money-input"><span>Rp</span><input type="number" min="0" step="1" required value={form.price} onChange={e => set("price", e.target.value)} /></div><small>{money.format(Number(form.price) || 0)}</small></Field><Field id="stock" label="Stok"><input type="number" min="0" step="1" required value={form.stock} onChange={e => set("stock", e.target.value)} /></Field><Field id="rating" label="Rating"><input type="number" min="0" max="5" step="0.1" required value={form.rating} onChange={e => set("rating", e.target.value)} /></Field></Grid></Section>
    <Section n="03" title="Variasi Produk"><Grid><Field id="flavor" label={parcel ? "Isi / Variasi Parcel" : "Flavor"} help={parcel ? "Masukkan isi atau variasi parcel yang ditawarkan." : "Contoh: Original, Pedas, atau Daun Jeruk."}><input value={form.flavor} onChange={e => set("flavor", e.target.value)} placeholder={parcel ? "Bawang Goreng Original + Pedas + Daun Jeruk" : "Original"} /></Field><Field id="size" label="Ukuran"><input value={form.size} onChange={e => set("size", e.target.value)} placeholder="Contoh: 100 gr" /></Field><Field id="badge" label="Badge (opsional)"><input value={form.badge} onChange={e => set("badge", e.target.value)} placeholder="Contoh: Best Seller" /></Field></Grid>{parcel && <div className="parcel-builder"><h3>Tambahan Parcel</h3><p>Hasil disimpan sebagai teks pada field flavor existing.</p><div><input aria-label="Isi parcel baru" value={draft} onChange={e => setDraft(e.target.value)} placeholder="Bawang Goreng Original" /><button type="button" onClick={() => { if (draft.trim()) { set("flavor", [...items, draft.trim()].join(", ")); setDraft(""); } }}><Plus size={18} /> Tambah Isi</button></div>{items.map((item, i) => <span key={`${item}-${i}`}>{item}<button type="button" aria-label={`Hapus ${item}`} onClick={() => set("flavor", items.filter((_, j) => i !== j).join(", "))}><X size={17} /></button></span>)}</div>}</Section>
    <Section n="04" title="Foto Produk"><input ref={fileRef} hidden type="file" accept="image/*" onChange={e => choose(e.target.files?.[0])} /><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={e => choose(e.target.files?.[0])} /><div className="photo-actions"><button type="button" onClick={openCamera}><Camera /> 📷 Ambil Foto</button><button type="button" onClick={() => fileRef.current?.click()}><ImagePlus /> ↑ Upload Foto</button></div><p className="helper">JPEG, PNG, atau WebP. Otomatis dioptimalkan ke maksimal 950 KB.</p>{photo || temporaryUrl ? <div className="photo-studio"><div className="photo-frame">{previewFailed ? <b>Preview tidak tersedia</b> : <Image src={photo?.url || temporaryUrl} alt={form.name || "Preview produk"} fill unoptimized onError={() => setPreviewFailed(true)} />}</div><div>{processing && <p><Loader2 className="spin" /> Memproses foto…</p>}{photo && <><dl><dt>Nama file</dt><dd>{photo.name}</dd><dt>Original</dt><dd>{size(photo.original)}</dd><dt>Optimized</dt><dd>{size(photo.final)}</dd><dt>Format</dt><dd>WebP</dd></dl><strong><Check /> Siap diupload</strong><div className="tools"><button type="button" aria-label="Crop foto" onClick={beginCrop}><Crop /> Crop</button><button type="button" aria-label="Putar kiri" onClick={() => edit(rotation - 90, crop)}><RotateCcw /> Kiri</button><button type="button" aria-label="Putar kanan" onClick={() => edit(rotation + 90, crop)}><RotateCw /> Kanan</button><button type="button" aria-label="Reset editor" onClick={() => edit(0, undefined)}>Reset</button><button type="button" aria-label="Hapus foto produk" onClick={removePhoto}><Trash2 /> Hapus</button></div></>}</div></div> : <div className="photo-empty"><ImagePlus /><b>Belum ada foto produk</b></div>}<div className="canva"><b>Edit di Canva</b><span>Integrasi Canva belum dikonfigurasi.</span></div></Section>
    {error && <p role="alert" className="studio-error">{error}</p>}<footer className="studio-footer"><button type="button" onClick={reset}>Reset</button><button disabled={busy || processing}>{busy ? <Loader2 className="spin" /> : <Save />} {busy ? "Menyimpan…" : "Simpan Produk"}</button></footer></div>
    <aside><Section n="05" title="Preview"><div className="product-preview"><div>{photo && !previewFailed ? <Image src={photo.url || temporaryUrl} alt={form.name || "Preview produk"} fill unoptimized onError={() => setPreviewFailed(true)} /> : photo ? <b>Preview tidak tersedia</b> : <ImagePlus />}{form.badge && <b>{form.badge}</b>}</div><article><small>{category?.name || "Kategori"}</small><h2>{form.name || "Nama Produk"}</h2><p>{form.flavor || (parcel ? "Isi parcel" : "Flavor produk")}{form.size && ` • ${form.size}`}</p><strong>{money.format(Number(form.price) || 0)}</strong><footer><span>Stok: {Number(form.stock) || 0}</span><b>{form.isActive ? "Aktif" : "Nonaktif"}</b></footer></article></div></Section></aside>
  </form></div>
  {cameraOpen && <div className="media-modal" role="dialog" aria-modal="true" aria-label="Camera Preview"><div><h2>Camera Preview</h2><video ref={videoRef} playsInline muted /><footer><button type="button" onClick={captureCamera}>Ambil Foto</button><button type="button" onClick={stopCamera}>Batal</button></footer></div></div>}
  {cropOpen && source && crop && <div className="media-modal" role="dialog" aria-modal="true" aria-label="Editor crop"><div><h2>Crop Foto</h2><div ref={cropRef} className="crop-preview" onPointerMove={moveCrop} onPointerUp={endCrop} onPointerCancel={endCrop}><Image src={temporaryUrl} alt="Crop preview" fill unoptimized /><span className="crop-box" role="application" aria-label="Area crop" onPointerDown={e => updateCrop(e, "move")} style={{ left: `${crop.x * 100}%`, top: `${crop.y * 100}%`, width: `${crop.size * 100}%`, height: `${crop.size * 100}%` }}><i aria-label="Geser sudut crop kiri atas" onPointerDown={e => { e.stopPropagation(); updateCrop(e, "resize", "top-left"); }} /><i aria-label="Geser sudut crop kanan atas" onPointerDown={e => { e.stopPropagation(); updateCrop(e, "resize", "top-right"); }} /><i aria-label="Geser sudut crop kiri bawah" onPointerDown={e => { e.stopPropagation(); updateCrop(e, "resize", "bottom-left"); }} /><i aria-label="Geser sudut crop kanan bawah" onPointerDown={e => { e.stopPropagation(); updateCrop(e, "resize", "bottom-right"); }} /></span></div><footer><button type="button" onClick={() => { setCropOpen(false); edit(rotation, crop); }}>Terapkan Crop</button><button type="button" onClick={() => { setCrop(cropBeforeEdit); setCropOpen(false); }}>Batal</button></footer></div></div>}
  </main>;
}
function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) { return <section className="studio-card"><header><b>{n}</b><h2>{title}</h2></header>{children}</section>; }
function Grid({ children, three }: { children: React.ReactNode; three?: boolean }) { return <div className={three ? "studio-grid three" : "studio-grid"}>{children}</div>; }
function Field({ id, label, help, children }: { id: string; label: string; help?: string; children: React.ReactNode }) { return <div className="studio-field"><label><span>{label}</span>{children}</label>{help && <small id={`${id}-help`}>{help}</small>}</div>; }