"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Ban, ChevronDown, ChevronRight, Download, Home, Loader2, LogOut, PackageSearch, User as UserIcon } from "lucide-react";
import jsPDF from "jspdf";
import { parseJsonResponse } from "@/lib/api-fetch";
import { getPaymentStatusPresentation } from "@/lib/payment-status";

type User = { id:string; name:string; email:string; phone:string|null; image:string|null; role:string; createdAt?:string };
type Item = { id:string; name:string; quantity:number; price?:number; subtotal:number; image?:string|null };
type Order = { id:string; invoice:string; createdAt:string; subtotal:number; shipping:number; discount?:number; total:number; voucher?:string|null; status:string; paymentStatus?:string; courier?:string|null; trackingNumber?:string|null; paidAt?:string|null; processedAt?:string|null; packedAt?:string|null; shippedAt?:string|null; completedAt?:string|null; cancelledAt?:string|null; items:Item[] };
type Filter = "Semua"|"Belum Bayar"|"Diproses"|"Selesai"|"Dibatalkan";
const filters:Filter[]=["Semua","Belum Bayar","Diproses","Selesai","Dibatalkan"];
const labels:Record<string,string>={pending:"Belum Bayar",PENDING:"Belum Bayar",processing:"Diproses",PROCESSING:"Diproses",packed:"Dikemas",PACKED:"Dikemas",shipped:"Dikirim",SHIPPED:"Dikirim",completed:"Selesai",COMPLETED:"Selesai",cancelled:"Dibatalkan",CANCELLED:"Dibatalkan"};
const tones:Record<string,string>={"Belum Bayar":"bg-[#fff2d6] text-[#8b5e00]",Diproses:"bg-[#e8f3ee] text-[#174c3a]",Dikemas:"bg-[#f5ebd8] text-[#76551d]",Dikirim:"bg-[#e8f0f3] text-[#245165]",Selesai:"bg-[#e8f3e3] text-[#29621a]",Dibatalkan:"bg-[#f7e9e6] text-[#8c2e25]"};
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0);
const date=(v?:string|null)=>v?new Date(v).toLocaleString("id-ID",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"-";
const status=(o:Order)=>labels[o.status]||o.status;
const price=(i:Item)=>i.price||Math.round(i.subtotal/(i.quantity||1));
const canCancel=(o:Order)=>o.status==="PENDING"||o.status==="pending";
const productImage=(i?:Item)=>i?.image||"/AFA LOGO.svg";

export function AccountDashboard({initialUser}:{initialUser:User}){
 const [orders,setOrders]=useState<Order[]>([]),[filter,setFilter]=useState<Filter>("Semua"),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[cancelTarget,setCancelTarget]=useState<Order|null>(null),[cancelling,setCancelling]=useState(false);
 const refresh=async()=>{const r=await fetch("/api/account/orders");if(r.ok)setOrders((await parseJsonResponse<{orders?:Order[]}>(r)).orders||[]);setLoading(false)};
 useEffect(()=>{void refresh()},[]);
 const counts=useMemo(()=>Object.fromEntries(filters.map(f=>[f,orders.filter(o=>f==="Semua"||(f==="Diproses"?["Diproses","Dikemas","Dikirim"].includes(status(o)):status(o)===f)).length])) as Record<Filter,number>,[orders]);
 const shown=orders.filter(o=>filter==="Semua"||(filter==="Diproses"?["Diproses","Dikemas","Dikirim"].includes(status(o)):status(o)===filter));
 const logout=async()=>{const r=await fetch("/api/auth/logout",{method:"POST"});if(r.ok)location.href="/";else setMessage("Logout gagal. Silakan coba lagi.")};
 const confirmCancel=async()=>{if(!cancelTarget)return;setCancelling(true);try{const r=await fetch(`/api/account/orders/${cancelTarget.id}/cancel`,{method:"POST"});const data=await r.json().catch(()=>null);if(r.ok){setMessage("Pesanan berhasil dibatalkan.");setFilter("Dibatalkan");setOpen(null);await refresh();}else setMessage((data&&(data as {message?:string}).message)||"Gagal membatalkan pesanan. Silakan coba lagi.");}catch{setMessage("Gagal membatalkan pesanan. Silakan coba lagi.");}finally{setCancelling(false);setCancelTarget(null);}};
 return <main className="min-h-screen bg-[#f7f4ec] pb-24 text-[#17241d]">
   <header className="sticky top-0 z-30 border-b border-[#173f31]/10 bg-white/95"><div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4"><Link href="/" className="font-display text-xl font-bold text-[#123d2d]">AFA <span className="text-[#b18a3d]">STORE</span></Link><details className="group relative"><summary className="flex cursor-pointer list-none items-center gap-2 [&::-webkit-details-marker]:hidden"><span className="grid h-9 w-9 place-items-center overflow-hidden rounded-full bg-[#123d2d] text-xs font-bold text-[#e3c77b]">{initialUser.image?<Image src={initialUser.image} alt={initialUser.name} width={36} height={36} className="h-full w-full object-cover" unoptimized/>:initialUser.name.slice(0,2).toUpperCase()}</span><span className="hidden text-right sm:block"><b className="block max-w-32 truncate text-xs">{initialUser.name}</b><small className="text-[10px] text-[#7a817c]">Akun Saya</small></span><ChevronDown size={15}/></summary><div className="absolute right-0 mt-2 w-40 overflow-hidden rounded-xl bg-white text-xs shadow-lg"><Link href="/account" className="flex items-center gap-2 p-3 hover:bg-[#f7f4ec]"><UserIcon size={14}/> Akun Saya</Link><button onClick={()=>void logout()} className="flex w-full items-center gap-2 border-t p-3 text-left hover:bg-[#f7f4ec]"><LogOut size={14}/> Keluar</button></div></details></div></header>
  <div className="mx-auto max-w-4xl px-3.5 py-5"><h1 className="font-display text-2xl font-bold text-[#123d2d]">Pesanan Saya</h1><p className="mt-1 text-xs text-[#69736d]">Lihat status dan detail pesanan Anda.</p>
   <nav className="-mx-3.5 mt-4 overflow-x-auto px-3.5 pb-1 [scrollbar-width:none]"><div className="flex w-max gap-2">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`min-h-9 rounded-full border px-3 text-xs font-semibold ${filter===f?"border-[#123d2d] bg-[#123d2d] text-white":"border-[#ded9cc] bg-white"}`}>{f} <span className="ml-1.5 rounded-full bg-black/5 px-1.5 py-0.5">{counts[f]}</span></button>)}</div></nav>
   {message&&<p className="mt-3 rounded-xl bg-[#fff2d6] p-2 text-xs">{message}</p>}
    <section className="mt-3 grid gap-2.5">{loading?[1,2,3].map(x=><div key={x} className="h-32 animate-pulse rounded-2xl bg-white"/>):shown.length?shown.map(o=><Card key={o.id} order={o} open={open===o.id} toggle={()=>setOpen(open===o.id?null:o.id)} onCancel={setCancelTarget}/>):<div className="rounded-2xl border border-dashed bg-white py-10 text-center"><PackageSearch className="mx-auto text-[#b18a3d]"/><b className="mt-2 block text-sm">Belum ada pesanan</b></div>}</section>
  </div>
  {cancelTarget&&<Confirm onConfirm={()=>void confirmCancel()} onClose={()=>setCancelTarget(null)} busy={cancelling}/>}
  <Bottom/></main>
}

function Confirm({onConfirm,onClose,busy}:{onConfirm:()=>void;onClose:()=>void;busy:boolean}){return <div className="fixed inset-0 z-50 grid place-items-center bg-[#17241d]/45 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-sm rounded-2xl bg-white p-5 shadow-2xl"><div className="grid h-11 w-11 place-items-center rounded-full bg-red-50 text-red-600"><Ban size={22}/></div><h2 className="mt-3 font-display text-lg font-bold text-[#123d2d]">Batalkan Pesanan?</h2><p className="mt-1 text-sm text-[#69736d]">Apakah Anda yakin ingin membatalkan pesanan ini?</p><div className="mt-5 flex gap-2"><button onClick={onClose} disabled={busy} className="min-h-10 flex-1 rounded-xl border border-[#ded9cc] bg-white px-4 text-sm font-bold disabled:opacity-50">Kembali</button><button onClick={onConfirm} disabled={busy} className="inline-flex min-h-10 flex-1 items-center justify-center gap-1.5 rounded-xl bg-red-600 px-4 text-sm font-bold text-white hover:bg-red-700 disabled:opacity-60">{busy&&<Loader2 size={15} className="animate-spin"/>}{busy?"Membatalkan…":"Ya, Batalkan"}</button></div></div></div>}

function Card({order:o,open,toggle,onCancel}:{order:Order;open:boolean;toggle:()=>void;onCancel:(o:Order)=>void}){const i=o.items[0],s=status(o);return <article className="overflow-hidden rounded-2xl border border-[#e5e0d5] bg-white shadow-sm"><div className="grid grid-cols-[68px_minmax(0,1fr)] gap-3 p-3 sm:grid-cols-[78px_minmax(0,1fr)_150px]"><div className="relative h-[68px] overflow-hidden rounded-xl bg-[#faf8f2] sm:h-[78px]"><Image src={productImage(i)} alt={i?.name||"Produk"} fill className="object-contain p-2" unoptimized/></div><div className="min-w-0"><b className="break-all text-[11px] text-[#123d2d]">{o.invoice}</b><p className="text-[10px] text-[#858a86]">{date(o.createdAt)}</p><h2 className="mt-1 line-clamp-2 text-xs font-semibold">{i?.name||"Produk AFA STORE"}{o.items.length>1?` +${o.items.length-1} produk`:""}</h2>{i&&<p className="text-[10px] text-[#747b76]">{i.quantity} x {money(price(i))}</p>}</div><div className="col-span-2 flex items-center justify-between border-t pt-2 sm:col-span-1 sm:flex-col sm:items-end sm:border-0 sm:pt-0"><div className="sm:text-right"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${tones[s]||"bg-gray-100"}`}>{s}</span><small className="mt-1 block text-[9px] text-gray-500">Total Harga</small><b className="block text-xs text-[#123d2d]">{money(o.total)}</b></div><button onClick={toggle} className="flex min-h-9 items-center text-[11px] font-bold text-[#99742e]">{open?"Tutup":"Lihat Detail"}<ChevronRight size={14}/></button></div></div>{open&&<Detail order={o} onCancel={onCancel}/>}</article>}

function Detail({order:o,onCancel}:{order:Order;onCancel:(o:Order)=>void}){const pay=getPaymentStatusPresentation(o.paymentStatus),s=status(o),cancellable=canCancel(o);const pdf=()=>{const d=new jsPDF();d.setFontSize(18);d.text("AFA STORE - INVOICE",14,18);d.setFontSize(11);d.text(`Invoice: ${o.invoice}`,14,30);let y=44;o.items.forEach(i=>{d.text(`${i.name} x${i.quantity} - ${money(i.subtotal)}`,14,y);y+=8});d.text(`Subtotal: ${money(o.subtotal)}`,14,y+4);d.text(`Ongkir: ${money(o.shipping)}`,14,y+12);d.text(`Diskon: ${money(o.discount||0)}`,14,y+20);d.text(`Total: ${money(o.total)}`,14,y+30);d.save(`${o.invoice}.pdf`)};return <div className="border-t bg-[#fcfaf5] p-3 text-xs"><div className="grid gap-3 md:grid-cols-2"><div><b>Produk</b>{o.items.map(i=><div key={i.id} className="mt-2 flex items-center justify-between gap-2 rounded-xl bg-white p-2"><span className="flex min-w-0 flex-1 items-center gap-2"><span className="relative h-10 w-10 shrink-0 overflow-hidden rounded-lg bg-[#faf8f2]"><Image src={productImage(i)} alt={i.name} fill className="object-contain p-1" unoptimized/></span><span className="min-w-0 flex-1">{i.name}<small className="block text-gray-500">{i.quantity} x {money(price(i))}</small></span></span><b className="shrink-0">{money(i.subtotal)}</b></div>)}<Timeline order={o}/><div className="mt-2 rounded-xl bg-white p-3"><b>Tracking</b><p>Kurir: {o.courier||"Belum dipilih"}</p><p>No. resi: {o.trackingNumber||"Belum tersedia"}</p>{o.shippedAt&&<p>Status: {s}</p>}</div></div><aside className="rounded-xl bg-[#123d2d] p-4 text-white"><b>Ringkasan</b><Line l="Invoice" v={o.invoice}/><Line l="Subtotal" v={money(o.subtotal)}/><Line l="Ongkir" v={money(o.shipping)}/><Line l="Diskon" v={`- ${money(o.discount||0)}`}/><Line l="Total" v={money(o.total)}/><Line l="Status" v={s}/><Line l="Pembayaran" v={pay.label}/></aside></div><div className="mt-3 flex flex-wrap gap-2">{pay.canPay&&<Link href={`/payment/${o.invoice}`} className="rounded-lg bg-[#b18a3d] px-3 py-2.5 font-bold text-white">Bayar Sekarang</Link>}<button onClick={pdf} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2.5 font-bold"><Download size={14}/> Invoice PDF</button><button onClick={()=>onCancel(o)} disabled={!cancellable} className="inline-flex items-center gap-1.5 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 font-bold text-red-600 disabled:cursor-not-allowed disabled:border-[#e5e0d5] disabled:bg-[#f4f1ea] disabled:text-[#b3b7b4]"><Ban size={14}/> Batalkan Pesanan</button></div></div>}

function Timeline({order:o}:{order:Order}){const x=o.cancelledAt?[["Belum Bayar",o.createdAt],["Dibatalkan",o.cancelledAt]]:[["Belum Bayar",o.paidAt||o.createdAt],["Diproses",o.processedAt],["Dikemas",o.packedAt],["Dikirim",o.shippedAt],["Selesai",o.completedAt]];return <div className="mt-2 overflow-x-auto rounded-xl bg-white p-3"><b>Status / Timeline</b><div className="mt-2 flex min-w-max gap-4">{x.map(([l,d])=><div key={l} className="w-20"><span className={`block h-3 w-3 rounded-full ${d?"bg-[#b18a3d]":"bg-gray-200"}`}/><b className="text-[9px]">{l}</b><small className="block text-[8px] text-gray-500">{d?date(d):"Menunggu"}</small></div>)}</div></div>}
function Line({l,v}:{l:string;v:string}){return <p className="mt-2 flex justify-between gap-2 text-[10px] text-white/75"><span>{l}</span><span className="break-all text-right">{v}</span></p>}
function Bottom(){return <nav className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95"><div className="mx-auto grid h-16 max-w-md grid-cols-3">{[["Beranda","/",Home],["Pesanan","/account",PackageSearch],["Akun","/account",UserIcon]].map(([l,h,I],i)=><Link key={l as string} href={h as string} className={`flex flex-col items-center justify-center text-[10px] font-semibold ${i===1?"text-[#123d2d]":"text-gray-400"}`}>{i===1&&<span className="absolute top-0 h-0.5 w-8 bg-[#b18a3d]"/>}<I size={19}/>{l as string}</Link>)}</div></nav>}