"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion, useScroll } from "framer-motion";
import { ArrowUp, Check, ChevronRight, Heart, Menu, Minus, Moon, Package, Plus, Search, ShoppingCart, Sun, Trash2, Truck, User, X, Zap } from "lucide-react";
import { CartItem, useCart } from "@/context/cart-context";
import { formatRupiah, parcels, products, productSizes, testimonials } from "@/lib/data";

const waNumber = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "6287770000883";
const nav = ["Beranda", "Bawang Goreng", "Parcel Hampers", "Promo", "Tentang Kami", "Testimoni", "FAQ", "Kontak"];
const shippingOptions = { Cilegon: 10000, Serang: 15000, Anyer: 20000, Merak: 10000, "Luar Kota": 25000 } as const;
const voucherRates: Record<string, number> = {
  AFA10: 0.1,
  AFA20: 0.2,
};

function buildCheckoutMessage(cart: CartItem[], subtotal: number, shipping: number, discount: number, total: number) {
  const itemLines = cart.map((item) => `- ${item.name} x${item.qty} = ${formatRupiah(item.price * item.qty)}`).join("\n");

  return [
    "Halo AFA STORE.",
    "",
    "Saya ingin memesan:",
    "",
    itemLines,
    "",
    `Subtotal: ${formatRupiah(subtotal)}`,
    `Ongkir: ${formatRupiah(shipping)}`,
    `Diskon: ${formatRupiah(discount)}`,
    `Total: ${formatRupiah(total)}`,
    "",
    "Nama:",
    "Alamat:",
  ].join("\n");
}

export default function Home() {
  const [slide, setSlide] = useState(0), [cartOpen, setCartOpen] = useState(false), [dark, setDark] = useState(false);
  const [query, setQuery] = useState(""), [filter, setFilter] = useState("Semua"), [sort, setSort] = useState("featured");
  const [wishlist, setWishlist] = useState<string[]>([]);
  const [preview, setPreview] = useState<{ src: string; name: string } | null>(null), [zoom, setZoom] = useState(1);
  const { cart, subtotal, addToCart, increaseQty, decreaseQty, removeFromCart } = useCart();
  const { scrollYProgress } = useScroll();
  const cartItemCount = cart.reduce((total, item) => total + item.qty, 0);
  useEffect(() => { setWishlist(JSON.parse(localStorage.getItem("afa-wishlist") || "[]")); }, []);
  useEffect(() => localStorage.setItem("afa-wishlist", JSON.stringify(wishlist)), [wishlist]);
  useEffect(() => { const t = setInterval(() => setSlide((s) => (s + 1) % 2), 5000); return () => clearInterval(t); }, []);
  const visibleProducts = useMemo(() => products.filter((p) => (filter === "Semua" || p.category === filter) && p.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "low" ? a.price - b.price : sort === "high" ? b.price - a.price : b.rating - a.rating), [filter, query, sort]);
  const addCart = (item: { id: string; name: string; price: number; image: string }) => { addToCart(item); setCartOpen(true); };
  const checkoutWhatsApp = (shipping: number, discount: number) => {
    const finalTotal = subtotal + shipping - discount;
    const message = buildCheckoutMessage(cart, subtotal, shipping, discount, finalTotal);
    window.open(`https://wa.me/${waNumber}?text=${encodeURIComponent(message)}`, "_blank");
  };

  return <main className={dark ? "bg-[#07140c] text-white" : "text-[#102116]"}><motion.div className="fixed left-0 right-0 top-0 z-80 h-1 origin-left bg-[#d4af37]" style={{ scaleX: scrollYProgress }} />
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#063b20]/90 text-white backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center gap-5 px-4 py-3"><a href="#beranda" className="mr-2 flex items-center gap-2 text-3xl font-bold text-[#d4af37]"><Image src="/assets/logo.svg" alt="AFA STORE logo" width={40} height={40} priority />AFA STORE</a><div className="hidden flex-1 items-center rounded-full bg-white px-4 py-2 text-[#102116] shadow-xl md:flex"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari produk bawang goreng, parcel, dll..." className="w-full bg-transparent outline-none" /><Search size={20} /></div><button onClick={() => setDark(!dark)} className="rounded-full p-2 hover:bg-white/10">{dark ? <Sun /> : <Moon />}</button><button className="hidden items-center gap-1 md:flex"><Heart />Wishlist</button><button onClick={() => setCartOpen(true)} className="relative flex items-center gap-1"><ShoppingCart />Keranjang<span className="absolute -top-2 left-4 rounded-full bg-[#d4af37] px-1 text-xs text-[#063b20]">{cartItemCount}</span></button><button className="hidden items-center gap-1 md:flex"><User />Akun</button><Menu className="md:hidden" /></div><nav className="mx-auto hidden max-w-7xl justify-center gap-9 px-4 pb-3 text-sm md:flex">{nav.map((n) => <a key={n} href={`#${n.toLowerCase().replaceAll(" ", "-")}`} className="hover:text-[#d4af37]">{n}</a>)}</nav></header>
    <section id="beranda" className="relative overflow-hidden bg-[radial-gradient(circle_at_20%_10%,#2d8b49_0%,#063b20_42%,#031a10_100%)] px-4 py-16 text-white md:py-24"><HeroDecor spicy={!slide} /><AnimatePresence mode="wait"><motion.div key={slide} initial={{ opacity: 0, y: 36, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, x: -34, scale: 0.98 }} transition={{ duration: 0.7, ease: "easeOut" }} className="relative z-10 mx-auto grid max-w-7xl items-center gap-10 md:grid-cols-[1fr_0.9fr]"><div><motion.p initial={{ opacity: 0, x: -18 }} animate={{ opacity: 1, x: 0 }} className="mb-3 text-4xl italic text-[#d4af37]">{slide ? "Parcel Hampers" : "Bawang Goreng"}</motion.p><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="text-6xl font-bold leading-none md:text-8xl">PREMIUM</motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="mt-5 max-w-2xl text-2xl">{slide ? "Cocok untuk Lebaran, Pernikahan, Ulang Tahun, Natal, Tahun Baru, dan Hadiah Perusahaan" : "Gurih - Renyah - Tanpa Tepung"}</motion.p><motion.button whileHover={{ scale: 1.05, y: -3 }} className="gold-gradient mt-8 rounded-2xl px-8 py-4 font-bold text-[#063b20] shadow-2xl">{slide ? "Lihat Parcel" : "Belanja Sekarang"}</motion.button></div><HeroShowcase slide={slide} /></motion.div></AnimatePresence></section>
    <section className="mx-auto -mt-8 grid max-w-6xl gap-4 px-4 md:grid-cols-4"><Info icon={<Package />} title="100% Bawang Asli" desc="Berkualitas premium" /><Info icon={<Check />} title="Tanpa Tepung" desc="Sehat & alami" /><Info icon={<Zap />} title="Gurih & Renyah" desc="Tahan lama" /><Info icon={<Truck />} title="Kirim Indonesia" desc="Cepat & aman" /></section><section className="mx-auto grid max-w-6xl grid-cols-2 gap-5 px-4 py-12 md:grid-cols-5">{[["Bawang Goreng", "ON"], ["Parcel Hampers", "GIFT"], ["Promo", "SALE"], ["Best Seller", "TOP"], ["Produk Baru", "NEW"]].map(([name, icon]) => <motion.div whileHover={{ y: -8 }} key={name} className="glass rounded-3xl p-6 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#fff7df] text-2xl font-bold text-[#b88710]">{icon}</div><p className="mt-3 font-bold">{name}</p></motion.div>)}</section>
    <section id="bawang-goreng" className="mx-auto max-w-7xl px-4 py-8"><SectionTitle title="Produk Bawang Goreng" /><div className="mb-6 flex flex-wrap gap-3"><select onChange={(e) => setFilter(e.target.value)} className="rounded-full border px-4 py-2 text-[#102116]"><option>Semua</option><option>Original</option><option>Pedas</option><option>Daun Jeruk</option></select><select onChange={(e) => setSort(e.target.value)} className="rounded-full border px-4 py-2 text-[#102116]"><option value="featured">Rating terbaik</option><option value="low">Harga termurah</option><option value="high">Harga tertinggi</option></select>{productSizes.map((s) => <span key={s} className="rounded-full bg-white px-4 py-2 text-[#102116] shadow">{s}</span>)}</div><div className="grid gap-6 md:grid-cols-3">{visibleProducts.map((p) => <ProductCard key={p.id} item={p} wish={wishlist.includes(p.id)} onWish={() => setWishlist((w) => w.includes(p.id) ? w.filter((x) => x !== p.id) : [...w, p.id])} onAdd={() => addCart(p)} onPreview={() => { setPreview({ src: p.image, name: p.name }); setZoom(1); }} />)}</div></section>
    <section id="parcel-hampers" className="mx-auto max-w-7xl px-4 py-8"><SectionTitle title="Parcel Hampers" /><div className="grid gap-6 md:grid-cols-5">{parcels.map((p) => <ProductCard key={p.id} item={{ ...p, stock: 30 }} onAdd={() => addCart(p)} onPreview={() => { setPreview({ src: p.image, name: p.name }); setZoom(1); }} />)}</div></section><Promo /><Testimonials /><FAQ /><Footer /><Floating onCart={() => setCartOpen(true)} /><CartDrawer open={cartOpen} cart={cart} subtotal={subtotal} onClose={() => setCartOpen(false)} onCheckout={checkoutWhatsApp} increaseQty={increaseQty} decreaseQty={decreaseQty} removeFromCart={removeFromCart} /><ImagePreview preview={preview} zoom={zoom} onZoomIn={() => setZoom((z) => Math.min(2.5, z + 0.25))} onZoomOut={() => setZoom((z) => Math.max(1, z - 0.25))} onClose={() => setPreview(null)} /></main>;
}

function Info({ icon, title, desc }: { icon: React.ReactNode; title: string; desc: string }) { return <div className="glass rounded-3xl p-5 flex items-center gap-4"><span className="text-[#d4af37]">{icon}</span><div><b>{title}</b><p className="text-sm opacity-70">{desc}</p></div></div>; }
function SectionTitle({ title }: { title: string }) { return <div className="mb-6 flex items-center justify-between"><h2 className="text-3xl font-bold uppercase">{title}</h2><a className="flex items-center gap-1 text-sm text-[#14532d]">Lihat Semua <ChevronRight size={16} /></a></div>; }
const heroSlides = [
  ["/products/backround.jpeg"],
  ["/products/parcel 2.png"],
];
function HeroShowcase({ slide }: { slide: number }) { return <motion.div whileHover={{ scale: 1.02 }} className="relative mx-auto min-h-95 w-full max-w-155 md:min-h-130"><div className="absolute inset-x-10 top-12 h-72 rounded-full bg-[#d4af37]/35 blur-3xl" /><div className="absolute inset-x-6 bottom-4 h-24 rounded-full bg-black/35 blur-2xl" /><div className="absolute inset-6 rounded-[3rem] border border-white/15 bg-white/10 shadow-[0_35px_90px_rgba(0,0,0,0.35)] backdrop-blur-md" /><HeroProduct src={heroSlides[slide][0]} parcel={slide === 1} /></motion.div>; }
function HeroProduct({ src, parcel }: { src: string; parcel: boolean }) { return <motion.div initial={{ opacity: 0, y: 42, scale: 0.9 }} animate={{ opacity: 1, y: [0, -16, 0], scale: 1 }} transition={{ opacity: { duration: 0.5 }, scale: { duration: 0.55 }, y: { repeat: Infinity, duration: 5, ease: "easeInOut" } }} whileHover={{ scale: 1.06, y: -18 }} className="absolute inset-x-[8%] top-[4%] bottom-[8%] rounded-[2.5rem] bg-white/12 p-4 shadow-[0_28px_70px_rgba(0,0,0,0.42)] ring-1 ring-white/20 backdrop-blur-sm"><div className="absolute inset-4 rounded-4xl bg-linear-to-b from-white/20 to-[#d4af37]/10" /><Image src={src} alt={parcel ? "Parcel premium AFA STORE" : "Bawang goreng premium AFA STORE"} fill sizes="(min-width: 768px) 45vw, 92vw" className="object-contain p-4 drop-shadow-2xl" priority onError={(e) => { e.currentTarget.style.display = "none"; }} /><div className="absolute inset-5 -z-10 rounded-4xl bg-[linear-gradient(135deg,rgba(255,255,255,0.16),rgba(212,175,55,0.18))]" /></motion.div>; }
function HeroDecor({ spicy }: { spicy: boolean }) { return <div aria-hidden="true" className="pointer-events-none absolute inset-0"><motion.span animate={{ y: [0, -14, 0], rotate: [18, 28, 18] }} transition={{ repeat: Infinity, duration: 6 }} className="absolute left-[6%] top-[18%] text-5xl opacity-70">🍃</motion.span><motion.span animate={{ y: [0, 12, 0], rotate: [-12, -24, -12] }} transition={{ repeat: Infinity, duration: 7 }} className="absolute bottom-[13%] left-[45%] text-4xl opacity-60">🧅</motion.span>{spicy && <motion.span animate={{ y: [0, -16, 0], rotate: [20, 32, 20] }} transition={{ repeat: Infinity, duration: 5 }} className="absolute right-[8%] top-[15%] text-5xl opacity-75">🌶️</motion.span>}<div className="absolute right-[18%] top-[20%] h-64 w-64 rounded-full bg-[#d4af37]/25 blur-3xl" /><div className="absolute bottom-0 left-0 h-48 w-48 rounded-full bg-white/10 blur-3xl" /></div>; }
function ProductCard({ item, onAdd, onWish, wish, onPreview }: { item: { id: string; name: string; price: number; reviews: number; rating?: number; stock?: number; badge?: string; image: string }; onAdd: () => void; onWish?: () => void; wish?: boolean; onPreview: () => void }) { return <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} className="glass rounded-3xl p-4 text-[#102116]"><button onClick={onPreview} className="relative block h-56 w-full overflow-hidden rounded-2xl bg-linear-to-br from-[#fff7df] via-white to-[#f4e3b1] text-left"><Image src={item.image} alt={item.name} fill sizes="(min-width: 768px) 33vw, 100vw" className="object-contain p-3 transition duration-500 hover:scale-105" />{item.badge && <b className="absolute left-3 top-3 rounded-full bg-[#d4af37] px-3 py-1 text-xs text-[#063b20]">{item.badge}</b>}<span className="absolute bottom-3 left-3 rounded-full bg-[#063b20]/85 px-3 py-1 text-xs font-bold text-white">Lihat gambar</span></button><button onClick={onWish} className="relative -mt-52 ml-auto mr-3 grid rounded-full bg-white p-2 shadow"><Heart fill={wish ? "#d4af37" : "none"} /></button><h3 className="mt-44 font-bold">{item.name}</h3><p className="text-sm text-[#d4af37]">★★★★★ <span className="text-[#102116]">({item.reviews})</span></p><p className="mt-2 text-xl font-bold">{formatRupiah(item.price)}</p><p className="text-sm opacity-70">Stok {item.stock ?? 20} - Quick View</p><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={onAdd} className="rounded-xl bg-[#14532d] px-4 py-3 text-white"><ShoppingCart className="inline" size={18} /></button><button className="rounded-xl border border-[#14532d] px-4 py-3 font-bold text-[#14532d]">Beli Sekarang</button></div></motion.article>; }
function ImagePreview({ preview, zoom, onZoomIn, onZoomOut, onClose }: { preview: { src: string; name: string } | null; zoom: number; onZoomIn: () => void; onZoomOut: () => void; onClose: () => void }) { return <AnimatePresence>{preview && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-100 grid place-items-center bg-[#07140c]/90 p-4 backdrop-blur-md"><div className="w-full max-w-5xl overflow-hidden rounded-4xl bg-white p-4 text-[#102116] shadow-2xl"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-[#d4af37]">Preview Produk</p><h3 className="text-2xl font-bold">{preview.name}</h3></div><div className="flex items-center gap-2"><button onClick={onZoomOut} className="rounded-full border px-4 py-2 font-bold">-</button><span className="min-w-14 text-center font-bold">{Math.round(zoom * 100)}%</span><button onClick={onZoomIn} className="rounded-full border px-4 py-2 font-bold">+</button><button onClick={onClose} className="rounded-full bg-[#14532d] p-3 text-white"><X /></button></div></div><div className="relative h-[70vh] overflow-auto rounded-3xl bg-[#fff7df]"><div className="relative mx-auto h-full min-h-105 w-full transition-transform duration-300" style={{ transform: `scale(${zoom})`, transformOrigin: "center" }}><Image src={preview.src} alt={preview.name} fill sizes="100vw" className="object-contain" priority /></div></div></div></motion.div>}</AnimatePresence>; }
function Promo() { return <section id="promo" className="mx-auto grid max-w-7xl gap-6 px-4 py-10 md:grid-cols-2"><div className="rounded-4xl bg-[#14532d] p-10 text-white shadow-2xl"><p className="text-[#d4af37]">FLASH SALE</p><h2 className="text-5xl font-bold">Diskon 20%</h2><p>Gratis ongkir dan Beli 3 Gratis 1 untuk semua produk tertentu.</p><div className="mt-6 flex gap-3">{[["02", "Hari"], ["14", "Jam"], ["25", "Menit"], ["36", "Detik"]].map(([a, b]) => <div key={b} className="rounded-xl border border-white/20 p-4 text-center"><b className="text-2xl">{a}</b><p>{b}</p></div>)}</div></div><div className="glass rounded-4xl p-10"><h3 className="text-3xl font-bold">Newsletter & Instagram Feed</h3><p>Dapatkan resep bawang goreng, promo hampers, dan inspirasi hadiah premium.</p><input className="mt-6 w-full rounded-full border px-5 py-3 text-[#102116]" placeholder="Masukkan email Anda" /></div></section>; }
function Testimonials() { return <section id="testimoni" className="overflow-hidden py-10"><div className="mx-auto max-w-7xl px-4"><SectionTitle title="Testimoni Pelanggan" /></div><div className="flex w-max gap-5 animate-marquee">{[...testimonials, ...testimonials].map((t, i) => <div key={i} className="glass w-80 rounded-3xl p-6 text-[#102116]"><div className="mb-3 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#14532d] text-white">{t[0][0]}</div><div><b>{t[0]}</b><p className="text-sm">{t[1]}</p></div></div><p className="text-[#d4af37]">★★★★★</p><p>&quot;{t[2]}&quot;</p></div>)}</div></section>; }
function FAQ() { const qs = ["Apakah tanpa tepung?", "Berapa lama tahan?", "Apakah bisa COD?", "Apakah bisa kirim seluruh Indonesia?", "Apakah bisa custom parcel?"]; return <section id="faq" className="mx-auto max-w-4xl px-4 py-10"><SectionTitle title="FAQ" />{qs.map((q) => <details key={q} className="glass mb-3 rounded-2xl p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 opacity-75">Ya, tim AFA STORE siap membantu kebutuhan Anda dengan kualitas premium.</p></details>)}</section>; }
function Footer() { return <footer id="kontak" className="bg-[#063b20] px-4 py-12 text-white"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-4"><div><h2 className="text-4xl font-bold text-[#d4af37]">AFA STORE</h2><p>Pusat bawang goreng premium dan parcel hampers berkualitas.</p></div><div><b>Menu</b><p>Beranda<br />Bawang Goreng<br />Parcel Hampers<br />Promo</p></div><div><b>Kontak Kami</b><p>WhatsApp 0877-7000-0883<br />Instagram @afa.store.id<br />TikTok @afastore<br />Facebook AFA STORE</p></div><div><b>Google Maps</b><div className="mt-3 rounded-2xl bg-white/15 p-8">AFA STORE, Cilegon Banten</div></div></div></footer>; }
function WhatsAppIcon() { return <svg viewBox="0 0 32 32" aria-hidden="true" className="h-8 w-8"><path fill="currentColor" d="M16 3C8.8 3 3 8.8 3 15.9c0 2.3.6 4.5 1.7 6.5L3.1 29l6.8-1.6c1.9 1 4 1.5 6.1 1.5 7.2 0 13-5.8 13-12.9S23.2 3 16 3Zm0 23.7c-1.9 0-3.7-.5-5.3-1.4l-.4-.2-4 .9 1-3.9-.3-.4c-1.1-1.7-1.7-3.7-1.7-5.8 0-5.9 4.8-10.7 10.7-10.7s10.7 4.8 10.7 10.7S21.9 26.7 16 26.7Zm5.9-8c-.3-.2-1.9-.9-2.2-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-.3-.2-1.3-.5-2.5-1.5-.9-.8-1.5-1.8-1.7-2.1-.2-.3 0-.5.1-.6.1-.1.3-.3.5-.5.1-.2.2-.3.3-.5.1-.2 0-.4 0-.5 0-.2-.7-1.7-1-2.3-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.9-.8 2.1-1.5.3-.7.3-1.3.2-1.5-.1-.1-.3-.2-.6-.4Z" /></svg>; }
function Floating({ onCart }: { onCart: () => void }) { return <div className="fixed bottom-5 right-5 z-40 flex flex-col gap-3"><a href={`https://wa.me/${waNumber}`} aria-label="Chat WhatsApp" className="grid h-14 w-14 place-items-center rounded-full bg-linear-to-br from-[#35f17b] via-[#20c767] to-[#075e54] text-white shadow-2xl ring-4 ring-white/70 transition hover:-translate-y-1 hover:shadow-green-500/40"><WhatsAppIcon /></a><button onClick={onCart} className="grid h-14 w-14 place-items-center rounded-full bg-[#14532d] text-white"><ShoppingCart /></button><a href="#beranda" className="grid h-14 w-14 place-items-center rounded-full bg-[#d4af37]"><ArrowUp /></a></div>; }
type CartDrawerProps = { open: boolean; cart: CartItem[]; subtotal: number; onClose: () => void; onCheckout: (shipping: number, discount: number) => void; increaseQty: (id: string) => void; decreaseQty: (id: string) => void; removeFromCart: (id: string) => void };
function CartDrawer({ open, cart, subtotal, onClose, onCheckout, increaseQty, decreaseQty, removeFromCart }: CartDrawerProps) {
  const [area, setArea] = useState("Cilegon");
  const [voucher, setVoucher] = useState("");
  const [voucherError, setVoucherError] = useState("");
  const voucherCode = voucher.trim().toUpperCase();
  const voucherRate = voucherRates[voucherCode] ?? 0;
  const discount = Math.round(subtotal * voucherRate);
  const shipping = shippingOptions[area as keyof typeof shippingOptions];
  const total = subtotal + shipping - discount;
  const handleCheckout = () => { if (voucher && !voucherRate) { setVoucherError("Voucher tidak ditemukan"); return; } setVoucherError(""); onCheckout(shipping, discount); };

  return <AnimatePresence>{open && <motion.aside initial={{ x: 420 }} animate={{ x: 0 }} exit={{ x: 420 }} className="fixed right-0 top-0 z-90 h-full w-full max-w-md overflow-auto bg-white p-6 text-[#102116] shadow-2xl"><div className="mb-6 flex justify-between"><h2 className="text-2xl font-bold">Keranjang Belanja</h2><button onClick={onClose}><X /></button></div>{cart.length > 0 ? cart.map((i) => <div key={i.id} className="mb-4 flex items-center gap-3 border-b pb-4"><div className="relative h-16 w-16 overflow-hidden rounded-xl bg-[#fff7df]"><Image src={i.image} alt={i.name} fill sizes="64px" className="object-cover" /></div><div className="flex-1"><b>{i.name}</b><p>{formatRupiah(i.price)}</p><div className="mt-2 inline-flex items-center overflow-hidden rounded-full border border-[#14532d]/25 bg-[#fff7df]"><button onClick={() => decreaseQty(i.id)} aria-label={`Kurangi ${i.name}`} className="grid h-9 w-9 place-items-center text-[#14532d] hover:bg-[#14532d] hover:text-white"><Minus size={14} /></button><span className="min-w-10 text-center text-sm font-bold">{i.qty}</span><button onClick={() => increaseQty(i.id)} aria-label={`Tambah ${i.name}`} className="grid h-9 w-9 place-items-center bg-[#14532d] text-white hover:bg-[#184C3A]"><Plus size={14} /></button></div><p className="mt-1 text-sm font-bold">Subtotal {formatRupiah(i.price * i.qty)}</p></div><button onClick={() => removeFromCart(i.id)} aria-label={`Hapus ${i.name}`}><Trash2 size={18} /></button></div>) : <p className="py-8 text-center opacity-70">Keranjang masih kosong</p>}<select value={area} onChange={(e) => setArea(e.target.value)} className="mb-3 w-full rounded-xl border px-4 py-3">{Object.entries(shippingOptions).map(([name, price]) => <option key={name} value={name}>{name} - {formatRupiah(price)}</option>)}</select><input value={voucher} onChange={(e) => { setVoucher(e.target.value); setVoucherError(""); }} className="mb-2 w-full rounded-xl border px-4 py-3" placeholder="Voucher" />{voucherError && <p className="mb-3 text-sm font-bold text-red-600">{voucherError}</p>}<p>Subtotal: {formatRupiah(subtotal)}</p><p>Ongkir: {formatRupiah(shipping)}</p><p>Diskon: {formatRupiah(discount)}</p><h3 className="mt-4 text-2xl font-bold">Total {formatRupiah(total)}</h3><button onClick={handleCheckout} disabled={!cart.length} className="mt-5 w-full rounded-2xl bg-[#14532d] px-6 py-4 font-bold text-white disabled:opacity-40">Checkout via WhatsApp</button></motion.aside>}</AnimatePresence>;
}
