"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import type { Product } from "@/lib/products";
import { ProductCard } from "@/components/product-card";

type Props = { products: Product[]; loading: boolean; error: string; isWishlisted: (id: string) => boolean; toggleWishlist: (item: Product) => void; addCart: (item: Product) => void; addState: Record<string, "adding" | "added">; buyNow: (item: Product) => void; onRetry: () => void; carouselRef: React.RefObject<HTMLDivElement | null>; onPause: () => void; onResume: () => void; onPrevious: () => void; onNext: () => void };

export default function HomeFeaturedProducts({ products, loading, error, isWishlisted, toggleWishlist, addCart, addState, buyNow, onRetry, carouselRef, onPause, onResume, onPrevious, onNext }: Props) {
  return <section id="katalog" className="product-section mx-auto max-w-[1400px] scroll-mt-24 px-5 py-12 sm:px-8 lg:px-12"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#A7833A]">Favorit keluarga</p><h2 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Produk Pilihan</h2><p className="mt-2 text-[var(--muted)]">Produk favorit untuk kamu dan keluarga</p></div><a href="/produk" className="hidden items-center gap-1 text-sm font-bold text-[#A7833A] sm:flex">Lihat Semua <ChevronRight size={16} /></a></div>{loading ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="skeleton aspect-[.8] rounded-3xl" />)}</div> : error ? <div role="alert" className="rounded-3xl border border-[var(--border)] p-8 text-center"><p>{error}</p><button type="button" onClick={onRetry} className="mt-4 rounded-full bg-[#123524] px-5 py-2 text-white">Coba Lagi</button></div> : <div className="relative"><button type="button" onClick={onPrevious} aria-label="Produk sebelumnya" className="absolute -left-3 top-1/2 z-10 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-[#123524] text-white shadow-lg"><ChevronLeft size={18} /></button><div ref={carouselRef} onMouseEnter={onPause} onMouseLeave={onResume} onPointerDown={onPause} onPointerUp={onResume} className="scrollbar-none flex snap-x snap-mandatory gap-4 overflow-x-auto px-1 py-2">{products.map((product) => <div key={product.id} data-product-slide className="w-[78%] shrink-0 snap-start sm:w-[46%] md:w-[31%] lg:w-[23%] xl:w-[19%]"><ProductCard item={product} wish={isWishlisted(product.id)} onWish={() => toggleWishlist(product)} onAdd={() => addCart(product)} addState={addState[product.id]} onBuy={() => buyNow(product)} /></div>)}</div><button type="button" onClick={onNext} aria-label="Produk berikutnya" className="absolute -right-3 top-1/2 z-10 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-[#123524] text-white shadow-lg"><ChevronRight size={18} /></button></div>}</section>;
}