"use client";
import { useEffect, useState } from "react";
import { VisitLocationMap } from "@/components/maps/VisitLocationMap";
import { optimizeSalesVisitImage } from "@/lib/sales-visit-image";

export function SalesStoreRegistration({ onCreated }: { onCreated: (store: { id: string; name: string }) => void }) {
  const [form, setForm] = useState({ name: "", ownerName: "", phone: "", address: "", notes: "" });
  const [location, setLocation] = useState<{ latitude: number; longitude: number; accuracy: number; capturedAt: string } | null>(null);
  const [photo, setPhoto] = useState<{ url: string; path: string; originalName: string; originalSize: number; size: number; width: number; height: number } | null>(null);
  const [photoStatus, setPhotoStatus] = useState("Belum ada foto");
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  function locate() { setMessage(""); if (!navigator.geolocation) return setMessage("Browser ini belum mendukung lokasi."); navigator.geolocation.getCurrentPosition(p => setLocation({ latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy: p.coords.accuracy, capturedAt: new Date().toISOString() }), e => setMessage(e.code === 1 ? "Izin lokasi ditolak. Aktifkan izin lokasi lalu coba lagi." : "Lokasi tidak tersedia atau timeout. Coba lagi."), { enableHighAccuracy: true, maximumAge: 0, timeout: 15000 }); }
  async function image(file: File) { setPhotoStatus("Mengoptimalkan..."); try { if (file.size > 20 * 1024 * 1024) throw new Error("Foto sumber maksimal 20 MB."); const preview = URL.createObjectURL(file); setPhoto((old) => { if (old) URL.revokeObjectURL(old.url); return { url: preview, path: "", originalName: file.name, originalSize: file.size, size: 0, width: 0, height: 0 }; }); const optimized = await optimizeSalesVisitImage(file); setPhotoStatus("Mengunggah..."); const fd = new FormData(); fd.append("file", optimized.file); const r = await fetch("/api/sales/stores/photo", { method: "POST", body: fd }); const p = await r.json(); if (!r.ok) throw new Error(p.message); setPhoto({ url: p.url, path: p.path, originalName: file.name, originalSize: file.size, size: optimized.file.size, width: optimized.width, height: optimized.height }); setPhotoStatus("Siap diunggah"); } catch (e) { setPhotoStatus("Gagal"); setMessage(e instanceof Error ? e.message : "Foto gagal diproses."); } }
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!location) return setMessage("Ambil lokasi GPS sebelum menyimpan."); setSaving(true); setMessage(""); try { const r = await fetch("/api/sales/stores/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, latitude: location.latitude, longitude: location.longitude, photoPath: photo?.path || undefined }) }); const p = await r.json(); if (!r.ok) throw new Error(p.message); onCreated(p.store); } catch (e) { if (photo?.path) void fetch("/api/sales/stores/photo", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ path: photo.path }) }); setMessage(e instanceof Error ? e.message : "Toko gagal disimpan."); } finally { setSaving(false); } }
  useEffect(() => () => { if (photo?.url?.startsWith("blob:")) URL.revokeObjectURL(photo.url); }, [photo?.url]);
  return <form onSubmit={submit} className="sales-card space-y-3 rounded-2xl bg-white p-4 shadow-sm"><h2 className="text-lg font-black text-[#184D47]">Daftarkan Toko Baru</h2>{["name","ownerName","phone","address","notes"].map(key => <label key={key} className="block text-sm font-bold">{key === "name" ? "Nama toko" : key === "ownerName" ? "Nama pemilik" : key === "phone" ? "Telepon" : key === "address" ? "Alamat" : "Catatan"}<input required={key === "name"} value={form[key as keyof typeof form]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 h-12 w-full rounded-xl border border-[#123524]/15 px-3" /></label>)}<button type="button" onClick={locate} className="min-h-12 w-full rounded-xl border border-[#184D47] font-black">{location ? "✓ PERBARUI LOKASI SAYA" : "AMBIL LOKASI SAYA"}</button>{location && <VisitLocationMap {...location} />}{location && <p className="text-xs">✓ Lokasi berhasil ditemukan · akurasi ±{Math.round(location.accuracy)} meter</p>}<label className="block text-sm font-bold">Foto toko<input type="file" accept="image/*" capture="environment" onChange={e => e.target.files?.[0] && image(e.target.files[0])} className="mt-1 w-full" /></label>{photo && <div className="text-xs text-[#184D47]"><img src={photo.url} alt="Preview toko" className="mb-2 h-32 w-full rounded-xl object-cover" /><p>{photoStatus} · {photo.originalName} · asli {Math.ceil(photo.originalSize / 1024)} KB · hasil {photo.size ? `${Math.ceil(photo.size / 1024)} KB` : "-"} · {photo.width} × {photo.height}</p></div>}{message && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</p>}<button disabled={saving || photoStatus === "Mengoptimalkan..." || photoStatus === "Mengunggah..."} className="min-h-14 w-full rounded-2xl bg-[#184D47] font-black text-white disabled:opacity-60">{saving ? "MENYIMPAN..." : "SIMPAN & PILIH TOKO"}</button></form>;
}