"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { getPaymentStatusPresentation } from "@/lib/payment-status";
type Props = { invoice: string; total: number; paymentMethod: string; paymentStatus: string; qrisSrc: string; expiredAt?: string | null };
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);
export function PaymentProofForm({ invoice, total, paymentMethod, paymentStatus, qrisSrc, expiredAt }: Props) {
    const [status, setStatus] = useState(paymentStatus);
    const presentation = getPaymentStatusPresentation(status);
    useEffect(() => {
        if (!getPaymentStatusPresentation(status).isPending) return;
        const refresh = async () => { if (document.visibilityState !== "visible") return; const response = await fetch(`/api/payments/${encodeURIComponent(invoice)}`, { cache: "no-store" }); if (!response.ok) return; const data = await response.json() as { status?: string }; if (data.status) setStatus(data.status); };
        const interval = window.setInterval(() => void refresh(), 10000);
        return () => window.clearInterval(interval);
    }, [invoice, status]);
    const expiryText = expiredAt ? new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date(expiredAt)) : null;
    return <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section className="rounded-[24px] border border-white/70 bg-white/80 p-5 shadow-[0_20px_60px_rgba(18,53,36,0.10)] backdrop-blur md:p-6"><div className={`rounded-2xl p-5 ${presentation.tone}`}><p className="text-2xl font-black">{presentation.heading}</p><p className="mt-1 font-medium">{presentation.description}</p>{presentation.isPending && paymentMethod === "QRIS" && <p className="mt-2 font-semibold">Silakan scan QRIS dan selesaikan pembayaran.</p>}</div><div className="mt-5 flex items-center justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#C9A45B]">Metode Pembayaran</p><h2 className="mt-1 text-2xl font-bold text-[#123524]">{paymentMethod}</h2></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${presentation.tone}`}>{presentation.label}</span></div>{presentation.isPending && paymentMethod === "QRIS" && <div className="mt-5 rounded-[24px] bg-[#F8F5EE] p-4"><p className="font-semibold text-[#6D6558]">Tunjukkan / scan QRIS menggunakan aplikasi pembayaran Anda.</p><ul className="mt-3 grid grid-cols-2 gap-2 text-sm font-medium text-[#123524] md:grid-cols-3"><li>GoPay</li><li>OVO</li><li>DANA</li><li>ShopeePay</li><li>Mobile Banking</li><li>Aplikasi QRIS lainnya</li></ul></div>}{!presentation.isPending && <p className="mt-5 rounded-2xl bg-[#F8F5EE] p-4 text-sm font-semibold text-[#6D6558]">Status ini berasal dari payment authority dan tidak dapat diubah pelanggan.</p>}</section><aside className="rounded-[24px] bg-[#123524] p-6 text-white"><p className="text-sm text-white/70">Invoice</p><p className="mt-1 break-all font-bold">{invoice}</p><p className="mt-5 text-sm text-white/70">Total</p><p className="mt-1 text-2xl font-black">{money(total)}</p>{qrisSrc && presentation.isPending && <Image src={qrisSrc} alt="QRIS pembayaran" width={640} height={640} unoptimized className="mx-auto mt-6 h-auto w-full rounded-2xl bg-white p-3" />}{expiryText && presentation.isPending && <p className="mt-5 text-sm text-white/75">Batas pembayaran: {expiryText}</p>}{presentation.isPending && <p className="mt-4 text-xs text-white/60">Status diperbarui otomatis selama halaman aktif.</p>}</aside></div>;
}